Repository atlp-rwanda/elite-bn-frontend, pull requests merged in 2021-02, with the labels that each got.

#10 ft(landingPage):A responsive landing page
  .github/workflows/actionCI.yml
  .gitignore
  enzyme.config.js
  package-lock.json
  package.json
  public/index.html
  src/components/Home.js
  src/components/LandingPage/DropMenu.js
  src/components/LandingPage/Footer.js
  src/components/LandingPage/HotelCard.js
  src/components/LandingPage/NavBar.js
  src/components/LandingPage/Testimonials.js
  src/components/LandingPage/TestmonialCard.js
  src/components/LandingPage/TopHotels.js
  src/components/LandingPage/VideoCard.js
  src/images/JaneDoe.png
  src/images/hotel1.jpg
  src/images/hotel2.jpg
  src/images/hotel3.jpg
  src/images/test1.jpg
  src/skeletons/HomePage/Video.js
  src/store/index.js
  src/test/App.test.js
  src/test/components/App.test.js
  src/test/components/Home.test.js
  src/test/components/homePage.test.js
  tailwind.config.js
  webpack.config.js
Labels: feature

#14 fixing video skeleton loader
  package-lock.json
  package.json
  src/App.js
  src/components/LandingPage/Footer.js
  src/components/LandingPage/NavBar.js
  src/components/LandingPage/TestmonialCard.js
  src/components/LandingPage/VideoCard.js
Labels: bug

#7 ft user register
  .DS_Store
  .gitignore
  jest.config.js
  package-lock.json
  package.json
  src/.DS_Store
  src/Routes/index.js
  src/assets/.DS_Store
  src/assets/icons8-facebook.svg
  src/assets/icons8-google.svg
  src/assets/images/accomodationImage.png
  src/components/Footer/Footer.js
  src/components/Header/NavBar.js
  src/components/Header/navCSS.css
  src/components/LandingPage/DropMenu.js
  src/components/UI/Button/Button.js
  src/components/UI/Button/Button.module.css
  src/components/UI/Spinner/Spinner.js
  src/components/UI/socialSignin/SocialSignin.test.js
  src/components/UI/socialSignin/socialSignin.js
  src/constants/actionTypes.js
  src/constants/actions.js
  src/containers/Auth/Auth.js
  src/containers/Auth/Auth.module.css
  src/containers/Auth/Auth.test.js
  src/skeletons/Signup/SignupSkeleton.js
  src/store/actions/auth.js
  src/store/actions/counter.js
  src/store/actions/index.js
  src/store/index.js
  src/store/initialState.js
  src/store/reducers/auth.js
  src/store/reducers/counter.js
  src/styles.css
  src/test/App.test.js
  src/test/components/Button.test.js
  src/test/components/DropMenu.test.js
  src/test/components/Home.test.js
  src/test/components/Spinner.test.js
  src/test/redux/actions/auth.action.test.js
  src/test/redux/reducers/auth.test.js
  src/test/redux/reducers/counter.test.js
  tailwind.config.js
  webpack.config.js
Labels: Ready

#17 Add logout functionality
  package-lock.json
  package.json
  src/App.js
  src/Routes/index.js
  src/assets/blank.png
  src/components/Dashboard/NavBar.js
  src/components/Dashboard/Sidebar.js
  src/components/Dashboard/pages/Content.js
  src/components/Dashboard/pages/DashBoard.js
  src/components/Login.js
  src/store/actioncreators/handle.js
  src/store/actions/ActionTypes.js
  src/store/actions/LogoutAction.js
  src/store/actions/index.js
  src/store/index.js
  src/store/reducers/user.js
  src/test/components/DashBoard.test.js
  src/test/redux/actions/logout.test.js
  src/test/redux/reducers/logout.reducer.test.js
  src/test/redux/reducers/user.test.js
  src/utils/getUserInfo.js
  webpack.config.js
Labels: Ready
